# script to save deployment artifacts to temporary repository
# this can be removed after Trident is deployed

name: Push File

on: push

jobs:
  copy-deployment-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes artifacts folder
      uses: crykn/copy_folder_to_another_repo_action@v1.0.6
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'artifacts'
        destination_repo: 'sushiswap/trident-dev-deployments'
        destination_folder: 'artifacts'
        user_email: 'gasper@sushi.com'
        user_name: 'gasperbr'
    - name: Pushes deployments folder
      uses: crykn/copy_folder_to_another_repo_action@v1.0.6
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'deployments'
        destination_repo: 'sushiswap/trident-dev-deployments'
        destination_folder: 'deployments'
        user_email: 'gasper@sushi.com'
        user_name: 'gasperbr'